### ISSUE TITLE
Not working fuel-cells from sterling systems when RPM and  Avionic Systems are installed.

### ISSUE THREAD

**Issue by Mar-V24** [JonnyOThan/RasterPropMonitor#129] opened 2024-03-28 17:56 UTC
The Isue affects the MACE fuel cells.
The issue only apperas when a kerbal is at the craft.
The issue affects only non-default B9 subtyps

>KSP.log file
[KSP.log](https://github.com/JonnyOThan/RasterPropMonitor/files/14793622/KSP.log)
(the subtyps exist in ModuleManger cache)

>To Reproduce
-Installing RPM and Avionic Systems (with ckan)
-installing Sterling systems and dependcies
-Launching a Sterling systems Fuel cell, and a part with a kerbal

>Expected behavior
Corerct resource requierments as when a probe core is used

>Screenshots
![image2](https://github.com/JonnyOThan/RasterPropMonitor/assets/165313429/210b5552-42d7-41ff-936a-c05b22c5a620)
(should need Berylim, asks for Aluminium)

-KSP 1.12.3/5
-Windows

**Comment by JonnyOThan** [comment] 2024-03-29 01:45
Sounds like a dupe of #93, but I heard a report that this only occurs when MAS and RPM are installed together.  Quite likely the bug is solely in MAS, and is the same issue as #93, but it is triggered by RPM's presence via patches that add MAS modules whenever a RPM computer module is present.

**Closed by JonnyOThan** 2024-03-29 01:45 UTC
Labels: bug
